### ISSUE TITLE
JSON cannot be deleted on Windows because of PermissionError

### ISSUE THREAD

**Issue by danielearning** [semente/django-smuggler#65] opened 2019-12-02 07:55 UTC
Hi.

Reason: Load of JSON files fail when trying to delete the JSON file. 

Expected: Loading successful. No error. Temporary file deleted.

Reproducible: On Windows 10 (not tested in other OS), with any JSON.

Below, the traces.
===============================================

Request Method: | POST
-- | --
http://localhost:5000/admin/load/
2.2.1
PermissionError
[WinError 32] El proceso no tiene acceso al archivo porque está siendo utilizado por otro proceso: 'C:\\Users\\Ivan\\AppData\\Local\\Temp\\auth_34g73qrx.json'
C:\Users\Ivan\AppData\Local\conda\conda\envs\atavia\lib\site-packages\smuggler\views.py in form_valid, line 138
C:\Users\Ivan\AppData\Local\conda\conda\envs\atavia\python.exe
3.7.1
['C:\\ATAVIA\\src',  'C:\\Users\\Ivan\\AppData\\Local\\conda\\conda\\envs\\atavia\\python37.zip',  'C:\\Users\\Ivan\\AppData\\Local\\conda\\conda\\envs\\atavia\\DLLs',  'C:\\Users\\Ivan\\AppData\\Local\\conda\\conda\\envs\\atavia\\lib',  'C:\\Users\\Ivan\\AppData\\Local\\conda\\conda\\envs\\atavia',  'C:\\Users\\Ivan\\AppData\\Roaming\\Python\\Python37\\site-packages',  'C:\\Users\\Ivan\\AppData\\Local\\conda\\conda\\envs\\atavia\\lib\\site-packages',  'C:\\Users\\Ivan\\AppData\\Local\\conda\\conda\\envs\\atavia\\lib\\site-packages\\odf',  'C:\\Users\\Ivan\\AppData\\Local\\conda\\conda\\envs\\atavia\\lib\\site-packages\\odf',  'C:\\Users\\Ivan\\AppData\\Local\\conda\\conda\\envs\\atavia\\lib\\site-packages\\odf',  'C:\\Users\\Ivan\\AppData\\Local\\conda\\conda\\envs\\atavia\\lib\\site-packages\\odf',  'C:\\Users\\Ivan\\AppData\\Local\\conda\\conda\\envs\\atavia\\lib\\site-packages\\odf',  'C:\\Users\\Ivan\\AppData\\Local\\conda\\conda\\envs\\atavia\\lib\\site-packages\\odf',  'C:\\Users\\Ivan\\AppData\\Local\\conda\\conda\\envs\\atavia\\lib\\site-packages\\odf']
Lun, 2 Dic 2019 08:49:23 +0100

=================================================

C:\Users\Ivan\AppData\Local\conda\conda\envs\atavia\lib\site-packages\smuggler\views.py in form_valid

                    os.unlink(tmp_file)

Variable | Value
-- | --
__class__ | <class 'smuggler.views.LoadDataView'>
destination_path | 'C:\\Users\\Ivan\\AppData\\Local\\Temp\\auth_34g73qrx.json'
file_name | 'auth.json'
fixtures | ['C:\\Users\\Ivan\\AppData\\Local\\Temp\\auth_34g73qrx.json']
form | <ImportForm bound=True, valid=True, fields=(uploads)>
picked_files | []
prefix | 'auth'
self | <smuggler.views.LoadDataView object at 0x0000028927536CC0>
store | False
suffix | '.json'
tmp_file | 'C:\\Users\\Ivan\\AppData\\Local\\Temp\\auth_34g73qrx.json'
tmp_fixtures | ['C:\\Users\\Ivan\\AppData\\Local\\Temp\\auth_34g73qrx.json']
upload | <InMemoryUploadedFile: auth.json (application/json)>
uploads | [<InMemoryUploadedFile: auth.json (application/json)>]

==================================================

Please excuse the Spanish localization.

Regards

**Comment by jaap3** [comment] 2021-09-27 07:18
This seems to be a duplicate of #61 (and #75)

**Closed by jaap3** 2021-09-27 07:18 UTC
